### DSTS - Week 2
#### @ Ibrahim Radwan

In [2]:
import numpy as np

In [3]:
# Print the NumPy version and its configuration
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [7]:
# Create a zero vector of size 10
zeros= np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# Create a 1D array with values ranging from 10 to 50
range_arr = np.arange(10, 50)
print(range_arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# Reverse a vector (first element becomes last)
vec = np.arange(50)
print(vec)
vec = vec[::-1]
print(vec)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [9]:
# Create a 3x3 matrix with values ranging from 0 to 8
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [12]:
# Create a 3x3x3 array with random values
mat_rand = np.random.random((3,3,3))
print(mat_rand)

[[[0.44867468 0.9625845  0.63929967]
  [0.47969633 0.37458667 0.89235997]
  [0.70578959 0.27964846 0.2238946 ]]

 [[0.46123958 0.07126669 0.94038972]
  [0.09800796 0.68231513 0.77953029]
  [0.32501222 0.7596457  0.53160258]]

 [[0.95655426 0.67167977 0.56037888]
  [0.26628808 0.69954969 0.40231724]
  [0.75303921 0.08534394 0.14657555]]]


In [15]:
# Create a 10x10 array with random values and find the minimum and maximum values
mat = np.random.random((10,10))
print(mat)
mat_min, mat_max = mat.min(), mat.max()
print(mat_min, mat_max)

[[0.99062987 0.19528736 0.78682813 0.14585991 0.21102764 0.49598087
  0.72826521 0.5456255  0.12122799 0.54273587]
 [0.69407285 0.87762254 0.57835248 0.18910463 0.72302972 0.55621232
  0.61481188 0.85003628 0.09324129 0.41610996]
 [0.36548589 0.46367094 0.45360112 0.46494091 0.13410346 0.90992133
  0.62016743 0.49668469 0.67089089 0.01321706]
 [0.67741358 0.811005   0.44230546 0.97361279 0.99472473 0.86674648
  0.29039857 0.44012504 0.14201921 0.47528308]
 [0.46459085 0.76164425 0.94818298 0.81020805 0.50794832 0.63751458
  0.06278405 0.89813355 0.47134809 0.78615774]
 [0.78470968 0.08886911 0.11437451 0.64160874 0.84012102 0.99785462
  0.02627183 0.02536072 0.75033097 0.37883288]
 [0.82716282 0.76820049 0.92779463 0.21433112 0.91311431 0.50402534
  0.7623517  0.66897152 0.65008942 0.77909577]
 [0.60859169 0.2563978  0.04493953 0.54272408 0.23003167 0.69007866
  0.3691514  0.14207809 0.00736345 0.28787811]
 [0.03231156 0.18228643 0.75071794 0.09175785 0.26237042 0.03910723
  0.43206149

In [17]:
# Create a random vector of size 30 and find the mean value
vec = np.random.random(30)
print(vec)
m = vec.mean()
print(m)

[4.01420634e-01 4.15979542e-01 6.74617418e-01 5.75956089e-01
 6.81988685e-01 1.11508153e-01 6.19709427e-05 2.45011798e-01
 8.04691478e-01 5.77329191e-01 2.56928170e-01 6.09714046e-01
 5.84512088e-01 4.89570126e-01 5.26739636e-01 3.28225525e-01
 8.65972681e-01 2.58862433e-02 9.97675022e-03 3.44145891e-01
 2.05860241e-01 6.07222919e-01 6.89524650e-01 5.69543742e-02
 5.55875734e-01 9.40738445e-01 9.02668899e-01 3.60672088e-01
 6.06347017e-01 6.08640944e-01]
0.46882471415056115


In [18]:
# Create a 2d array with 1 on the border and 0 inside
mat = np.ones((10,10))
mat[1:-1,1:-1] = 0
print(mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [20]:
# Multiply a 5x3 matrix by a 3x2 matrix (matrix product)
mat = np.dot(np.ones((5,3)), np.ones((3,2)))
print(mat)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [21]:
# Write a NumPy program to multiply two given arrays of same size element-by-element.
nums1 = np.array([[2, 5, 2],
                  [1, 5, 5]])

nums2 = np.array([[5, 3, 4],
                  [3, 2, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))

Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]
